############################################################
# Dockerfile to build xpaas-bpmsuite image including:
# - OpenJDK 1.7.0
# - JBoss EAP 6.3.1
# - JBoss BPMS 6.1.0.DR4-redhat3
# Version: 6.1
############################################################

####### BASE ############
#FROM docker-registry.usersys.redhat.com/goldmann/jboss-bpms:6.1
FROM jboss-eap:6.3

####### MAINTAINER ############
MAINTAINER "JBoss XPaaS Team" "xpass-eng@redhat.com"

####### RDBMS DRIVERS ############
USER root
RUN yum install -y postgresql-jdbc mysql-connector-java


#ENV JBOSS_HOME /opt/jboss/eap
ENV CONTAINER_CONFIG /opt/jboss/bpms


# BPM Suite 6.1 zip file
ENV BPM_ZIP jboss-bpmsuite-6.1.0.GA-deployable-eap6.x.zip
ENV BPM_ZIP_PATH /resources/$BPM_ZIP

# JBoss EAP configuration variables
# ENV JBOSS_BIND_ADDRESS 127.0.0.1 // Not set. By default uses the runnig docker container's ip address.

# Default values for database connection variables
ENV BPMS_CONNECTION_URL "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
ENV BPMS_CONNECTION_DRIVER h2
ENV BPMS_CONNECTION_USER sa
# TODO: Docker best practices - Do not use passwords here 
ENV BPMS_CONNECTION_PASSWORD sa

# Cluster related envs
# ENV BPMS_CLUSTER_NAME // Not set by default
# ENV BPMS_ZOOKEEPER_SERVER // Not set by default
ENV BPMS_VFS_LOCK bpms-vfs-lock
# ENV BPMS_GIT_HOST // Set by default to the container's ip address
ENV BPMS_GIT_PORT 9520
ENV BPMS_GIT_DIR $CONTAINER_CONFIG/vfs
# ENV BPMS_SSH_HOST // Set by default to the container's ip address
ENV BPMS_SSH_PORT 9521
ENV BPMS_INDEX_DIR $CONTAINER_CONFIG/index
ENV BPMS_QUARTZ_PROPERTIES $CONTAINER_CONFIG/quartz-db.properties
# TODO: Docker best practices - Do not use passwords here
ENV BPMS_CLUSTER_PASSWORD bpmsclustering
ENV BPMS_CLUSTER_NODE 1
ENV HELIX_VERSION 0.6.3
ENV HELIX_HOME /opt/jboss/helix


#######  Layer BPM Suite 6 on EAP ####
ADD ./resources /resources
RUN unzip -o $BPM_ZIP_PATH -d /tmp/
RUN cp -r /tmp/jboss-eap-6.3/* $JBOSS_HOME
RUN rm -rf /tmp/jboss-eap-6.3
RUN mkdir -p $CONTAINER_CONFIG/index $CONTAINER_CONFIG/vfs

####### CUSTOM JBOSS USER ############
# Switchback to jboss user
USER jboss 

####### HELIX ############
RUN curl --silent --output /opt/jboss/helix.tar http://ftp.cixug.es/apache/helix/$HELIX_VERSION/binaries/helix-core-$HELIX_VERSION-pkg.tar; \ 
tar -xvf helix.tar; \ 
mv helix-core-$HELIX_VERSION helix; \ 
rm helix.tar


####### BPMS CUSTOM CONFIGURATION ############
# There is an issue in Docker with ADD command.
# When a file is added into the container's filesystem, the file owner is always root, instead of the current running user.
# See https://github.com/docker/docker/issues/5110
# The workaround is doing a chown using root user and then switchback to jboss user.
ADD etc/modules $CONTAINER_CONFIG/modules
ADD etc/standalone-full-ha.xml.template $JBOSS_HOME/standalone/configuration/standalone-full-ha.xml.template
ADD etc/bpms-users.properties $JBOSS_HOME/standalone/configuration/bpms-users.properties
ADD etc/bpms-roles.properties $JBOSS_HOME/standalone/configuration/bpms-roles.properties
ADD etc/mgmt-users.properties $JBOSS_HOME/standalone/configuration/mgmt-users.properties
ADD etc/persistence.xml.template $JBOSS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/META-INF/persistence.xml.template
ADD etc/start-bpms.sh $CONTAINER_CONFIG/start-bpms.sh
ADD etc/quartz-db.properties $CONTAINER_CONFIG/quartz-db.properties
ADD etc/use_remote_hq_broker.cli $CONTAINER_CONFIG/use_remote_hq_broker.cli
USER root
RUN chown -R jboss:jboss $JBOSS_HOME
RUN chown -R jboss:jboss $CONTAINER_CONFIG

# Assign a shell to jboss user so as to allow switching to this user
RUN usermod -s /bin/bash jboss

# Add the executable flag.
RUN chmod +x $CONTAINER_CONFIG/start-bpms.sh

# Expose CLI as well as BPMS git & ssh ports
EXPOSE 9999 9520 9521

# Switchback to jboss user
USER jboss

####### RUNNING BPMS ############
CMD ["/opt/jboss/bpms/start-bpms.sh"]
